# Generated by Django 4.2.8 on 2025-07-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpCode',
        ),
    ]
