# Generated by Django 4.2.15 on 2024-12-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('valid_from', models.CharField(max_length=250)),
                ('valid_to', models.CharField(max_length=250)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
