# Generated by Django 4.2.8 on 2025-03-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_register_date_customer_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ensurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
