# Generated by Django 4.2.8 on 2025-03-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_birthday_customer_ensurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_code',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
