# Generated by Django 4.2.8 on 2025-03-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_customer_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedcourse',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
