# Generated by Django 4.2.8 on 2025-03-11 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_customer_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
