# Generated by Django 4.2.8 on 2025-03-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_customer_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('national_code', models.CharField(max_length=250)),
                ('courses', models.ManyToManyField(blank=True, to='shop.coursetitle')),
            ],
        ),
        migrations.AddField(
            model_name='reservedcourse',
            name='Instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.instructor'),
        ),
    ]
