# Generated by Django 4.2.8 on 2025-03-12 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_instructor_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('pay_month', models.IntegerField(default=1)),
                ('pay_year', models.IntegerField(default=1403)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.instructor')),
            ],
        ),
    ]
