# Generated by Django 4.2.8 on 2025-03-12 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_instructor_reservedcourse_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedcourse',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
