# Generated by Django 4.2.8 on 2025-03-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_reservedcourse_register_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorMonthlyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=1403)),
                ('courses', models.ManyToManyField(blank=True, to='shop.reservedcourse')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.instructor')),
            ],
        ),
    ]
