# Generated by Django 4.2.8 on 2025-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_instructormonthlyincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='share_percent',
            field=models.IntegerField(default=70),
        ),
    ]
