# Generated by Django 4.2.8 on 2025-03-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_instructormonthlyincome_is_payed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructormonthlyincome',
            old_name='is_payed',
            new_name='is_paid',
        ),
    ]
