# Generated by Django 4.2.8 on 2025-03-13 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_is_payed_instructormonthlyincome_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructormonthlyincome',
            name='pay_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
