# Generated by Django 4.2.8 on 2025-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_paymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedcourse',
            name='register_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
